На пути к совершенству
htmlacademy-yii/249461-task-force-1 pull request #5
Opened 2021-04-05 06:14 UTC by kravtsov-s-o

2021-04-05 08:12 UTC, nikserg requested changes
В целом правильно, но есть возможность улучшить

2021-04-05 08:12 UTC, nikserg commented on src/model/actions/AbstractAction.php
> +    abstract function getActionSystemName();
Мне кажется, внутреннее название - это избыточно. В этом качестве можно использовать просто имя класса, типа
`CanceledAction::class`

2021-04-05 08:12 UTC, nikserg commented on src/model/Task.php
> +                if ($action->userRoleCheck($this->idClient, $this->idExecutor, $id)) {
В целом правильно, но можно сократить.
Например, используя currentStatus внутри switch определить класс действия, а потом вызвать userRoleCheck только один раз.
Типа

```
$class = null;
switch ($currentStatus) {
 case self::STATUS_NEW:
   $class = RespondAction::class;
   break;
 ...
}
$model = new $class();
if ($model->userRoleCheck(...)) {
return $model;
}
...
```

2021-04-05 08:24 UTC, kravtsov-s-o commented on src/model/actions/AbstractAction.php
> +    abstract function getActionSystemName();
По заданию, должен быть метод который возвращает внутренее название:

_Этот класс имеет три публичных метода для возврата названия, внутреннего имени и для проверки прав._

2021-04-09 04:55 UTC, kravtsov-s-o commented on src/model/Task.php
> +                if ($action->userRoleCheck($this->idClient, $this->idExecutor, $id)) {
Исправил

2021-04-09 06:39 UTC, merged